class AppSecrets{
  static const supabaseUrl="https://jukanhonmcvrwcvpdxgy.supabase.co";
  static const supabaseAnonKey="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1a2FuaG9ubWN2cndjdnBkeGd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzAwMTQxOTksImV4cCI6MjA0NTU5MDE5OX0.-1poL1ZwpuvtpfwCx3uPwqcqCxKLHPiSMdJYWNg-Ijk";
}